language: generic
sudo: required

before_install:
  - "mkdir -p ~/.npm"

install:
  - ./install-bikeshed.sh

script:
  - ./travis.sh

env:
  global:
  - TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"
  - COMMIT_USER="$(git log --format=%an --no-merges -n 1)"
  - COMMIT_EMAIL="$(git log --format=%ae --no-merges -n 1)"
  - ENCRYPTION_LABEL: "faa8d02310a6"

notifications:
  email:
  - bbirtles@mozilla.com
